### ISSUE TITLE
静态文件结尾带有斜杠没有返回301

### ISSUE THREAD

**Issue by Zeno-Code** [teambition/gear#13]
`app.Use(static.New(static.Options{
	Root: "./public",
}))`

127.0.0.1 GET /static/banner.jpg/ 200 57683 - 0.000 ms

**Comment by zensh** [comment]
这个目前还真不好处理，因为 `static` 中间件利用了原生的 `http.ServeFile`。ServeFile 内部实现其实有判断这个逻辑 https://github.com/golang/go/blob/master/src/net/http/fs.go#L574，但是，没有启用~ https://github.com/golang/go/blob/master/src/net/http/fs.go#L671

gear 自己实现这一套的话意义并不大，只能坐等 go 语言修复了~

**Comment by zensh** [comment]
先关闭了，一方面等 Golang 官方修复；另一方面这个影响极小
