### ISSUE TITLE
建议改为dep来控制依赖

### ISSUE THREAD

**Issue by zhangweilun** [teambition/gear#16]
项目依赖建议

**Comment by zensh** [comment]
主要是 dep 连文件格式都还没确定啊，等格式定下来就可以用它了，一直在关注 https://github.com/golang/dep/issues/276

**Comment by dbsn** [comment]
gear看起来很不错，另外毕竟是公司开发的，感觉比个人开发的靠谱。
就是希望文档更多些，最好加上案例教程。
当年beego之所以能火起来，详实的文档功不可没。

**Comment by zensh** [comment]
@dbsn 会要加上来 😆

**Comment by moocss** [comment]
@zensh Gear团队加油，再多丰富一些example，不过 KPass也是非常好的参考。

**Comment by dbsn** [comment]
C:\Users\huang>go get  -u github.com/teambition/gear
# cd E:\GP\src\github.com\teambition\gear; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/teambition/gear: exit status 128

之前可以的，现在不能用 go get -u 了？

**Comment by zensh** [comment]
git pull --ff-only:
```
--ff-only
           Refuse to merge and exit with a non-zero status unless the current HEAD is already up-to-date or the merge can be resolved as a fast-forward.
```
