### ISSUE TITLE
undefined: http.ErrAbortHandler

### ISSUE THREAD

**Issue by rockdean** [teambition/gear#20]
ritsus-iMac:fingerprint zhaoyili$ go get github.com/teambition/gear
`# github.com/teambition/gear
src/github.com/teambition/gear/app.go:343: undefined: http.ErrAbortHandler
src/github.com/teambition/gear/app.go:386: app.Server.Shutdown undefined (type *http.Server has no field or method Shutdown)
src/github.com/teambition/gear/app.go:388: app.Server.Close undefined (type *http.Server has no field or method Close)
src/github.com/teambition/gear/response.go:169: undefined: http.PushOptions
src/github.com/teambition/gear/response.go:170: undefined: http.Pusher
src/github.com/teambition/gear/util.go:354: undefined: url.PathEscape`

**Comment by zensh** [comment]
go v1.8.0 required

**Comment by rockdean** [comment]
谢谢，后面我发现了,是这个问题.
