### ISSUE TITLE
app.Server.serve(listener) not work

### ISSUE THREAD

**Issue by orangemi** [teambition/gear#35]
```go
app := gear.New()
app.Use(func(ctx *gear.Context) error {
	return ctx.HTML(200, "Hello World")
})
listener, _ := net.Listen("tcp", ":9090")
app.Server.Serve(listener)
```
It won't response `Hello World` for any request.
I think add `app.Server.Handler = app` in `New()` may help. So is `app.Server.ErrorLog = app.logger`.

**Comment by zensh** [comment]
Why not use app.Listen?
There are some logic between `server.ListenAndServe` and `server.Serve`.
