### ISSUE TITLE
关于 SetOnError 的回调方法

### ISSUE THREAD

**Issue by isayme** [teambition/gear#43]
目前对于 SetOnError 的回调要求格式是`func(ctx *Context, err HTTPError)`.

当前的预期(个人理解)是: 使用者在回调方法里处理`err`并调用 `ctx.End` 之类的方法.

存在的问题有:
1. `err` 是 `ParseError` 处理后的对象, 使用者无法知道原始错误信息;
2. 无法使用 `ctx.Error` 响应数据, 会存在死循环;

### 解决办法
将回调的格式改为 `func(ctx *Context, err error) error`:
当返回新的 error 时, gear 使用新的 error 交给 `ParseError` 处理, 否则还是使用原`err`;

> 这个方法并没有解决回调里调用`ctx.Error`导致的死循环问题.

带来的好处是: 用户可以拿到原始 error 并处理, 然后返回给 gear 继续处理;

当然, 这个方法是存在兼容问题的! 解决办法是: 回调函数支持两种方式
对于旧的方式, 再包装成新的格式.
```
func (ctx *Context, err error) error {
    fn(ctx, ParseError(err, ctx.Res.status()))
    return nil // 返回 nil 表示已经自行处理过
}
```
如果使用旧的方式, 打印一个 deprecated warning 信息.

**Comment by zensh** [comment]
该方法本意是让用户能自定义错误响应内容，比如输出 html 的错误页面

**Comment by isayme** [comment]
嗯, 我改了一版, 现在 github 抽风, 推不上来~~

**Comment by zensh** [comment]
增加一个 SetParseError 的配置如何？
