### ISSUE TITLE
route /user/:id 不应该能适配到/user/  这样的

### ISSUE THREAD

**Issue by nyrf** [teambition/gear#53]
现在如果设置一个路由 `/user/:id`，然后访问 `localhost:3000/user/` 也是适配到 `/user/:id` 这个路由的，正常这种应该是适配到 `/user` 的吧？

**Comment by zensh** [comment]
因为默认开启了 TrailingSlashRedirect，如果不需要这种行为，可以关闭它，见
https://github.com/teambition/gear/blob/master/router.go#L137
